### ISSUE TITLE
Run tests without relying on subprocesses

### ISSUE THREAD

**Issue by embray** [embray/d2to1#19]
Currently the d2to1 tests launch in a subrocess to minimize environmental impact and to achieve more accurate functional testing.  But the setuptools sandbox environment might prove just as effective (I've used them before for testing other setup utilities).

The current method using subprocesses also makes gathering test coverage data too difficult.  I'm not sure if that situation will be any better with sandboxing but it's worth a try.

**Comment by RonnyPfannschmidt** [comment]
recent coverage and co_core has utilities for subprocesses

**Comment by embray** [comment]
@RonnyPfannschmidt Interesting, thanks for pointing that out.  I didn't know that that's been improved.

That said, for the next d2to1 (or more likely its successor, whichever comes first) I'll more likely just use `setuptools.sandbox`.  All the tests for [astropy-helpers](https://github.com/astropy/astropy-helpers) use this without launching any subprocesses, and it has proven quite effective (with the appropriate tweaks here and there).  And a lot of tests for astropy-helpers are actually more complex than anything in d2to1's tests :)

**Comment by merwok** [comment]
What is co_core?

**Comment by embray** [comment]
I wondered that myself--figured it was some profiler I hadn't heard of, but now that I bother googling it I don't see anything.

**Comment by RonnyPfannschmidt** [comment]
@embray please utterly avoid the setuptools sandbox, its a horrible hack

**Comment by embray** [comment]
It's fine for testing.  Useful, even.
