### ISSUE TITLE
the parsing of version specifiers does not match PEP345

### ISSUE THREAD

**Issue by graingert** [embray/d2to1#27]
http://www.python.org/dev/peps/pep-0345/#version-specifiers

`zope.interface (3.1)`

becomes `zope.interface3.1` but it should be `zope.interface>=3.1,<3.2`

**Comment by embray** [comment]
Closing in preparation for project archival: https://github.com/embray/d2to1/blob/master/README.rst#deprecated  Thanks for all your help with this project!
